apiVersion: v1
kind: Namespace
metadata:
  name: flux
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flux
  namespace: flux
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: flux
  namespace: flux
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: flux
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: flux-readonly
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: flux
  namespace: flux
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: flux
subjects:
- kind: ServiceAccount
  name: flux
  namespace: flux
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: flux
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flux
subjects:
- kind: ServiceAccount
  name: flux
  namespace: flux
---
apiVersion: v1
data:
  kubeconfig.yaml: |-
    apiVersion: v1
    kind: Config
    preferences: {}
    users: []
    clusters: []
    current-context: default
    contexts:
    - context:
        cluster: ""
        namespace: flux
        user: ""
      name: default
kind: ConfigMap
metadata:
  name: flux-kube-config-785chkggdd
  namespace: flux
---
apiVersion: v1
kind: Service
metadata:
  name: flux-metrics
  namespace: flux
spec:
  ports:
  - name: metrics
    port: 9121
    protocol: TCP
    targetPort: 9121
  selector:
    app: flux
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: memcached
  namespace: flux
spec:
  ports:
  - name: memcached
    port: 11211
    protocol: TCP
    targetPort: memcached
  selector:
    app.kubernetes.io/name: memcached-deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flux
  name: flux
  namespace: flux
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flux
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: flux
    spec:
      containers:
      - args:
        - --memcached-hostname=memcached.flux
        - --memcached-service=
        - --ssh-keygen-dir=/var/fluxd/keygen
        - --git-user="Weave Flux"
        - --git-email="tnowak@noreply.github.com"
        - --listen-metrics=:9121
        - --manifest-generation=true
        - --sync-garbage-collection
        - --git-ci-skip
        - --docker-config=/docker/config.json
        - --git-url=git@github.com:ionfury/flux-test
        - --git-branch=private-playground
        #- --git-branch=master
        - --git-path=manifests/spin
        - --git-sync-tag=flux-sync7
        - --git-poll-interval=1m
        - --git-timeout=20s
        - --sync-interval=1m
        - --sync-timeout=80s
        - --k8s-verbosity=5
        env:
        - name: KUBECONFIG
          value: /root/.kubectl/kubeconfig.yaml
        - name: CHECKPOINT_DISABLE
          value: "true"
        #image: docker.io/fluxcd/flux:1.21.0
        image: localhost:5000/flux:v15
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /api/flux/v6/identity.pub
            port: 3030
          initialDelaySeconds: 5
          timeoutSeconds: 5
        name: flux
        ports:
        - containerPort: 3030
        - containerPort: 9121
          name: http-metrics
        readinessProbe:
          httpGet:
            path: /api/flux/v6/identity.pub
            port: 3030
          initialDelaySeconds: 5
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 1
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 64Mi
        volumeMounts:
        - name: git-key
          mountPath: /etc/fluxd/ssh 
          readOnly: true
        - mountPath: /root/.kubectl
          name: kubedir
        - mountPath: /var/fluxd/keygen
          name: git-keygen
      serviceAccountName: flux
      volumes:
      - configMap:
          name: flux-kube-config-785chkggdd
        name: kubedir
      - emptyDir:
          medium: Memory
        name: git-keygen  
      - name: git-key
        secret:
          secretName: flux-git-deploy
          defaultMode: 0400 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: memcached-deployment
  name: memcached
  namespace: flux
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: memcached-deployment
  template:
    metadata:
      labels:
        app.kubernetes.io/name: memcached-deployment
    spec:
      containers:
      - args:
        - -m 512
        - -I 5m
        - -p 11211
        image: memcached:1.5.20
        imagePullPolicy: IfNotPresent
        name: memcached
        ports:
        - containerPort: 11211
          name: memcached
        resources:
          limits:
            cpu: 1
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 120Mi
        securityContext:
          allowPrivilegeEscalation: false
          runAsGroup: 11211
          runAsUser: 11211
---
apiVersion: v1
kind: Secret
metadata:
  name: flux-git-deploy
  namespace: flux
type: Opaque